# Dummy config.toml for testing

main.plugins.memtemp.enabled = true
main.plugins.grid.enabled = true
main.ai.enabled = true
personality.sad_num_epochs = 25
main.plugins.WebUI_data.enabled = false
personality.bored_num_epochs = 15
personality.excited_num_epochs = 10
main.name = "Pwnstro-Bot"
main.whitelist = [
  "your_home_network_ssid",
  "your_phone_hotspot_ssid"
]
ui.display.enabled = true
ui.display.type = "waveshare_2"
ui.display.color = "black"
main.plugins.grid.report = true
main.ai.learning_rate = 0.001
main.ai.epsilon_start = 0.9
